### PR TITLE
fix: use fileURLToPath for mimicked __dirname

### LINKED ISSUE #562: Fails with `Error: ENOENT: no such file or directory` on Windows
**What version of secretlint are you using?**

7.0.2
*`npx secretlint --version` also fails, so based on the `package.json` in `node_modules`

**What did you do? Please include the actual steps causing the issue.**

The following repository might reproduce the bug but it may reproduce only in Windows. Please ignore the repo name since I first thought it was a bug due to pnpm.

https://github.com/risu729/secretlint-pnpm-test

Just follow the installation steps in README.
1. Run `npm install secretlint @secretlint/secretlint-rule-preset-recommend --save-dev`
2. Run `npx secretlint --init --debug`

**What did you expect to happen?**

The command runs successfully and create `.secretlintrc.json`

**What actually happened? Please include the actual, raw output from secretlint.**

```
Error: ENOENT: no such file or directory, scandir '\C:\Users\taku\Documents\GitHub\insta-spyglass\node_modules\.pnpm\@secretlint+formatter@7.0.2\node_modules\@secretlint\formatter\module\formatters'
    at Object.readdirSync (node:fs:1533:3)
    at secretlintGetFormatterList (file:///C:/Users/taku/Documents/GitHub/insta-spyglass/node_modules/.pnpm/@secretlint+formatter@7.0.2/node_modules/@secretlint/formatter/module/index.js:139:10)
    at getFormatterList (file:///C:/Users/taku/Documents/GitHub/insta-spyglass/node_modules/.pnpm/@secretlint+formatter@7.0.2/node_modules/@secretlint/formatter/module/index.js:132:34)        
    at file:///C:/Users/taku/Documents/GitHub/insta-spyglass/node_modules/.pnpm/secretlint@7.0.2/node_modules/secretlint/module/cli.js:18:94
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:246:24)
    at async file:///C:/Users/taku/Documents/GitHub/insta-spyglass/node_modules/.pnpm/secretlint@7.0.2/node_modules/secretlint/bin/secretlint.js:14:26 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '\\C:\\Users\\taku\\Documents\\GitHub\\insta-spyglass\\node_modules\\.pnpm\\@secretlint+formatter@7.0.2\\node_modules\\@secretlint\\formatter\\module\\formatters'
}
```

**Solution**

The path starts with `\C:\` seems to be the cause. It should start with `C:\`.
The mimic of `__dirname` causes that, so I would create a PR to fix it.

### PR DESCRIPTION
**Pull request by risu729**
Fix the __dirname mimic to remove a leading slash in it by using fileURLToPath instead.

Closes #562.

Ref: https://humanwhocodes.com/snippets/2023/01/mimicking-dirname-filename-nodejs-esm/

I checked through the repo and replaced all `__dirname`.

### CODE REVIEW

**Comment by azu** [comment]
Thanks.

Huh? I wonder why Windows CI has been going through until now.

**Comment by azu** [comment]
https://github.com/secretlint/secretlint/blob/6eadd51964e16de4c95ced6621ae9067b023830e/packages/%40secretlint/quick-start/src/index.ts#L5
@secretlint/quick-start also need to be updated?

**Comment by risu729** [comment]
I missed that part, sorry. I fixed it, so it should work now.

File: packages/@secretlint/quick-start/src/index.ts [hunk 1]
```diff
@@ -1,8 +1,10 @@
+import { fileURLToPath } from "node:url";
+import path from "node:path";
 import { cli, run } from "secretlint/cli";
 
 export const quickStart = async () => {
     // Override secretlintrc with quick-start pkg if it is not defined.
-    const defaultSecretlintRc = new URL("../config/.secretlintrc.json", import.meta.url).pathname;
+    const defaultSecretlintRc = path.resolve(fileURLToPath(import.meta.url), "../config/.secretlintrc.json");
```
Comment (azu) [inline packages/@secretlint/quick-start/src/index.ts:7]: fileURLToPath(import.meta.url) point to packages/@secretlint/quick-start/module/index.js

```
> path.resolve("packages/@secretlint/quick-start/src/index.ts", "../config/.secretlintrc.json")
'/Users/azu/ghq/github.com/textlint/textlint/packages/textlint/packages/@secretlint/quick-start/src/config/.secretlintrc.json'
```

```suggestion
    const __dirname = path.dirname(fileURLToPath(import.meta.url));
    const defaultSecretlintRc = path.resolve(__dirname, "../config/.secretlintrc.json");
```

is correct?

Comment (risu729) [reply packages/@secretlint/quick-start/src/index.ts]: Thanks for your help! I agree with it.

**Comment by azu** [comment]
Thanks!
