### PR TITLE
fix(config-loader)!: secretlint rule should `export { creator }`

### LINKED ISSUE #190: use `export cosnt creator` instead of `export default`
We will change rule definition.

## Changes

Secretlint rule should exports next properties.

- `messages`: messsages is messages id and value
- `creator`: a rule implementation

### Remove

Remove to support `export default creator` and `module.exports = creator`.
It will be replaced by named export.

## Motivation

This changes is strange behavior of dynamic import in CommonJS.

```
❯ cat export.cjs
module.exports = 1;

❯ cat export.mjs
export default 1;

❯ cat export_transpiled.cjs
Object.defineProperty(exports, '__esModule', { value: true })
module.exports.default = 1;
```

import above modules by dynamic import.

```js
import("./export.cjs").then(cjs => {
    console.log("cjs", cjs);
});
import("./export_transpiled.cjs").then(cjs => {
    console.log("cjs_transpiled", cjs);
});
import("./export.mjs").then(mjs => {
    console.log("mjs", mjs);
});

/*
mjs [Module: null prototype] { default: 1 }
cjs [Module: null prototype] { default: 1 }
cjs_transpiled [Module: null prototype] { __esModule: true, default: { default: 1 } }
*/
```

`cjs_transpiled` result is very strange but it is expected.

We need to use `.default.default` to import transpiled code by tsc or babel.
#187  is implemented align that.

However, we can chagne the rule interface to use named export.

If a rule use only named exports, we do not worry about the `default.default` property.

```js
Object.defineProperty(exports, '__esModule', { value: true })
module.exports.a = "a";
module.exports.default = 1;
```

```
cjs_transpiled [Module: null prototype] {
  __esModule: true,
  a: 'a',
  default: { a: 'a', default: 1 }
}
```

### PR DESCRIPTION
**Pull request by azu**
## Breaking Changes

- `export const creator = { ... }` instead of `export deafult creator`

There is no 3rd-party secretlint rules https://github.com/search?q=secretlint-rule&type=Repositories
So, This is not affect to any users.

## Updates

- Update rule docs

fix #190

### CODE REVIEW

File: packages/@secretlint/config-loader/src/index.ts [hunk 1]
```diff
@@ -5,16 +5,20 @@ import {
...
-        return (moduleExports as any).default?.default!;
+export function importSecretlintCreator(moduleExports?: SecretLintRuleModule): SecretLintUnionRuleCreator {
+    if (!moduleExports) {
+        throw new Error("Secretlint rule should export { creator }. module is undefined");
     }
-    return moduleExports && (moduleExports as any).default ? (moduleExports as any).default! : moduleExports;
+    if (!("creator" in moduleExports)) {
+        throw new Error("Secretlint rule should export { creator }. module does not export creator object.");
+    }
+    return moduleExports.creator;
```
Comment (azu) [inline packages/@secretlint/config-loader/src/index.ts:21]: Just use `mod.creator`
