### PR TITLE
fix(aws): report only found Access key

### LINKED ISSUE #32: aws: should report only access key
image

https://github.com/secretlint/secretlint/blob/c137c00829d6ee903d0e81894e0d343fff94f089/packages/@secretlint/secretlint-rule-aws/src/index.ts#L102
Currenly, report matching all. 

We should improve it. Report only Access Key.

### PR DESCRIPTION
**Pull request by azu**
fix #32

### CODE REVIEW

File: packages/@secretlint/secretlint-rule-aws/src/index.ts [hunk 1]
```diff
@@ -172,6 +172,7 @@ export const creator: SecretLintRuleCreator<Options> = {
         const t = context.createTranslator(messages);
         return {
             file(source: SecretLintSourceCode) {
+                console.log(source, options);
```
Comment (azu) [inline packages/@secretlint/secretlint-rule-aws/src/index.ts]:
```suggestion
```

File: packages/@secretlint/secretlint-rule-aws/test/index.test.ts [hunk 2]
```diff
@@ -7,15 +7,15 @@ describe("Snapshot Testing", () => {
...
-                    options: {}
+                    id: require("../package.json").name,
+                    rule
                 }
             ]
         },
         updateSnapshot: !!process.env.UPDATE_SNAPSHOT,
         snapshotDirectory: path.join(__dirname, "snapshots")
     }).forEach((name, test) => {
+        console.log("name", name);
```
Comment (azu) [inline packages/@secretlint/secretlint-rule-aws/test/index.test.ts]:
```suggestion
```
