### PR TITLE
fix(core): change SecretLintRuleMessageTranslate to check statically

### LINKED ISSUE #119: core: does not format user's data that include placeholder-like string
Curentlly, This test does not be passed.

https://github.com/secretlint/secretlint/blob/c2445ccd7db13c559bff269b8e5d2dfda1936200/packages/%40secretlint/core/test/helper/SecretLintRuleMessageTranslator.test.ts#L80-L101

```diff
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected ... Lines skipped

  {
    data: {
...
      v3: '{{v1}} {{v2}} {{v3}}'
    },
+   message: '{{v1}} {{v1}} {{v2}} {{v1}} {{v2}} {{v3}} {{v1}} {{v2}} {{v3}} {{v1}} {{v2}} {{v1}} {{v2}} {{v3}} {{v1}} {{v2}} {{v3}} message',
-   message: '{{v1}} {{v2}} {{v3}} {{v1}} {{v2}} {{v3}} {{v1}} {{v2}} {{v3}} message',
    messageId: 'messageId'
  }
```

We want to fix this.

### LINKED ISSUE #124: core: Can context.createTranslator check data statically?
Currently, `context.createTranslator` check only messageIds statically.
The `data` (second parameter of `t` function) is not checked statically.

Ths `data` is checked in runtime. It is related with #119 
 
```ts
import { SecretLintRuleCreator, SecretLintSourceCode } from "@secretlint/types";

// MessageIds
export const messages = {
    EXAMPLE_MESSAGE: {
        en: "found secret: {{ID}}",
        ja: "secret: {{ID}} がみつかりました"
    }
};

export const creator: SecretLintRuleCreator = {
    messages,
    meta: {
        // rule.meta.id should be same with package.json name
        id: "@secretlint/secretlint-rule-example",
        recommended: false,
        // type
        type: "scanner",
        // support content types: "text" or "binary" or "all"
        supportedContentTypes: ["text"],
        // Documentation Base URL for the package
        docs: {
            url:
                "https://github.com/secretlint/secretlint/blob/master/packages/%40secretlint/secretlint-rule-example/README.md"
        }
    },
    // Rule Logic
    create(context) {
        // Create Traslate instance
        const t = context.createTranslator(messages);
        return {
            // source has `content`, `filePath` etc...
            file(source: SecretLintSourceCode) {
                const pattern = /secret/gi;
                let match;
                while ((match = pattern.exec(source.content)) !== null) {
                    const index = match.index || 0;
                    const matchString = match[0] || "";
                    const range = [index, index + matchString.length];
                    // Report found "secret"
                    context.report({
                        // Replace "found secret: {{ID}}" with `ID` data
                        message: t("EXAMPLE_MESSAGE", {
                            ID: matchString
                        }),
                        range
                    });
                }
            }
        };
    }
};
// export it as default
export default creator;
```

## Idea

I think that to change `mesages` syntax, It can be checked statically?
This idea come from JSX/React.

```ts
// illust
const mesages = {
  hi: (props: {a: string}) => `text ${props.a}`,
  hello: {
    en: (props: {b: string}) => `text ${props.b}`,
    ja:  (props: {b: string}) => `text ${props.b}`,
  }
}

translate(mesages.hi, {
  a: "name"
});
translate(mesages.hello, {
  b: "name"
});
```

### PR DESCRIPTION
**Pull request by azu**
BREAKING CHANGE: It changes SecretLintRuleMessageTranslate interface

Each rule need to change `messages` object format.

```diff
    AWSAccessKeyID: {
-        en: "found AWS Access Key ID: {{ID}}",
-        ja: "AWS Access Key Id: {{ID}} がみつかりました"
+        en: (props: { ID: string }) => `found AWS Access Key ID: ${props.ID}`,
+        ja: (props: { ID: string }) => `AWS Access Key Id: ${props.ID} がみつかりました`,
    },
```

It will resolve #119 because, it also remove runtime check for placeholder string.
It introduce static check for template string instead of non-typed placeholder string.

cons:

The message is not be string. message in JSON can not be used any more.

fix #119 
fix #124

### CODE REVIEW

File: packages/@secretlint/config-validator/src/SecretLintConfigDescriptor-validation.ts [hunk 1]
```diff
@@ -108,38 +111,34 @@ export const SecretLintConfigDescriptorSchema = {
...
-            "type": "string"
+            "properties": {
+              "en": {
+                "$ref": "#/definitions/SecretLintRuleLocalizeMessageHandler"
+              }
+            },
+            "required": [
+              "en"
+            ],
+            "type": "object"
```
Comment (azu) [inline packages/@secretlint/config-validator/src/SecretLintConfigDescriptor-validation.ts:127]: fm. it should be function

File: packages/@secretlint/types/src/SecretLintRuleTranslator.ts [hunk 2]
```diff
@@ -14,24 +14,35 @@ export type SecretLintRuleLocaleTag =
...
+export type SecretLintRuleLocalizeMessageProps = { [index: string]: any };
+
+export type SecretLintRuleLocalizeMessageHandler<Props extends SecretLintRuleLocalizeMessageProps> = (
+    props?: Props
+) => string;
+export type SecretLintRuleLocalizeMessageMulti<Props extends SecretLintRuleLocalizeMessageProps> = {
+    [P in SecretLintRuleLocaleTag]: SecretLintRuleLocalizeMessageHandler<Props>;
+} & {
+    // Workaround for https://github.com/YousefED/typescript-json-schema/issues/110
+    en(props?: Props): string;
```
Comment (azu) [inline packages/@secretlint/types/src/SecretLintRuleTranslator.ts:26]: https://github.com/YousefED/typescript-json-schema/issues/110 does not support `function`.
It should be ignored.

**Comment by azu** [comment]
- [ ] Need to update docs
